windows_openssh_service_state: started
windows_openssh_firewall_port: 22
windows_openssh_default_shell: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe

temp_dir: C:\Temp

virtio_version: 0.1.266-1
virtio_base_url: https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio
virtio_gt_filename: virtio-win-gt-x64.msi

winfsp_version: 2.0.23075
winfsp_base_url: https://github.com/winfsp/winfsp/releases/download/v2.0

spice_url: https://www.spice-space.org/download/windows/spice-guest-tools/spice-guest-tools-latest.exe
